### ISSUE TITLE
Problem after update Gnome to 3.33.*

### ISSUE THREAD

**Issue by mokilcde** [pitcer/text-translator#4]
Hi!

After upgrade to Gnome 3.33.x (current 3.33.91) I git this error:
text-translator_pitcer.pl has error: TypeError: Object 0x7fbf90aaed60 is not a subclass of GObject_Object, it's a Object

**Comment by chama-chomo** [comment]
Please keep this extension updated if you can. I've found it very useful

**Comment by AmyangXYZ** [comment]
> Please keep this extension updated if you can. I've found it very useful

If this extension is not maintained anymore, you can try [crow translate](https://github.com/crow-translate/crow-translate), works in the same way

**Comment by chama-chomo** [comment]
thanks, I'll use as a WA until this one gets resurrected

EDIT: I have created a little bit simpler interface to crow using rofi

```
#!/usr/bin/env bash

STRING=$(rofi -dmenu -lines 1)
RESULT=$(crow -t sk+en "${STRING}")
rofi -e  "${RESULT}" -fullscreen
```

**Comment by pitcer** [comment]
Hi, please try the latest version of extension.

**Comment by chama-chomo** [comment]
I can't make it working

```
 gnome-shell[23533]: JS ERROR: Extension text-translator@pitcer.pl: TypeError: this._init_most_used_bar is not a function
                                                  TranslatorDialog@/home/cqs/.local/share/gnome-shell/extensions/text-translator@pitcer.pl/translator_dialog.js:344:9
                                                  TranslatorExtension@/home/cqs/.local/share/gnome-shell/extensions/text-translator@pitcer.pl/extension.js:248:24
                                                  enable@/home/cqs/.local/share/gnome-shell/extensions/text-translator@pitcer.pl/extension.js:840:18
                                                  _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:131:13
                                                  loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:263:21
                                                  callback@resource:///org/gnome/shell/ui/extensionDownloader.js:232:17
                                                  gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:99:13
```

**Comment by chama-chomo** [comment]
it works now for me, thanks
